# Generated by Django 3.0.8 on 2020-08-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsstory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='image',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.CharField(default='https://picsum.photos/600', max_length=2000),
        ),
    ]
