# Generated by Django 3.0.8 on 2020-08-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200808_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['status', '-created_on']},
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(blank=True, choices=[('N', 'National'), ('G', 'Global'), ('L', 'Lifestyle'), ('V', 'Travel'), ('E', 'Entertainment'), ('T', 'Technology'), ('F', 'Finance'), ('S', 'Sport')], default='', help_text='Choose one or more', max_length=1),
        ),
    ]
