# Generated by Django 3.0.8 on 2020-08-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200810_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this story', to='news.Category'),
        ),
    ]
