# Generated by Django 3.0.8 on 2020-08-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200810_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['-status', '-pub_date']},
        ),
    ]
